### ISSUE TITLE
Faceshifter: Catch 404 errors on message fetch

### ISSUE THREAD

**Issue by sinus-x** [sinus-x/rubbergoddess#177]
Catch the exception and send information to stdout channel and notification to botdev channel.

```
Traceback (most recent call last):
  File "/.../discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/.../faceshifter.py", line 177, in on_raw_message_edit
    message = await message_channel.fetch_message(payload.message_id)
  File "/.../discord/abc.py", line 956, in fetch_message
    data = await self._state.http.get_message(channel.id, id)
  File "/.../discord/http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

The information should contain at least the user, channel and message link.

**Comment by sinus-x** [comment]
If we remove the react-to-role prefix (we still have the `?role` command), we can test the channel ID before fetching anything.

https://github.com/sinus-x/rubbergoddess/blob/e66e7c35128518fe69016898bdd240e287156d1e/cogs/faceshifter/faceshifter.py#L175-L181

```py
async def on_raw_message_edit(self, payload: discord.RawMessageUpdateEvent):
  if payload.channel_id not in self.config.get("r2r_channels"):
    return

  # code
```
