### ISSUE TITLE
Voice is broken

### ISSUE THREAD

**Issue by sinus-x** [sinus-x/rubbergoddess#85]
Since yesterday, the `?voice rename` command does not work -- the command does nothing and after ~8 minutes, an error is thrown:
```
Ignoring exception in command voice rename: 

Traceback (most recent call last):
  ...
  File "/home/rubbergoddess/rubbergoddess/cogs/voice.py", line 83, in voice_rename
    await v.edit(name=name)
  ...
  File "/home/rubbergoddess/.local/lib/python3.7/site-packages/discord/http.py", line 223, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10003): Unknown Channel
```

**Comment by sinus-x** [comment]
There seems to be problem with caching and updating from the library side. I'm removing the v0.4 milestone, we need more time to find proper solution.
